### ISSUE TITLE
Problematic Install on OS X Yosemite

### ISSUE THREAD

**Issue by Nicholas-Westby** [specialunderwear/Hosts.prefpane#26]
I tried installing this (version 1.3) and I got stuck on this screen with a spinning beachball (this was after I clicked "Install" but before it asks to enter my credentials):
![locked](https://cloud.githubusercontent.com/assets/5933222/8111913/62145d26-1019-11e5-9834-3aba85ad87ff.png)

I was on that screen for 5-10 minutes before I restarted (had to force quit the installer). I then ran the installer again before I started any other programs and it worked fine. I'm on Yosemite 10.10.3:
![yosemite](https://cloud.githubusercontent.com/assets/5933222/8111966/aa454790-1019-11e5-9cc1-2d821fc6565f.png)

**Comment by specialunderwear** [comment]
I've got problems with the installer myself as well. It seems to work for most people though. I'm planning to get rid of it. It's useless and only there for people that don't have any idea what to do with a .prefPane file.

**Comment by paultreny** [comment]
Double-clicking a .prefpane file should be within most users' capabilities, I'd hope!

**Comment by TopCheff** [comment]
hola, Yo tengo el mac del 2011 y me ha dejado instalarlo sin problema. revisa que tengas acceso como administrador.
