### ISSUE TITLE
How to uninstall this app?

### ISSUE THREAD

**Issue by imranismail** [specialunderwear/Hosts.prefpane#27]

**Comment by oliveratgithub** [comment]
@imranismail go to the folder where the Preference Pane was installed (depending if 1. only for your user or 2. the whole system)

`/Users/[YourUsername]/Library/PreferencePanes/`

`/Volumes/[YourMacHD]/Library/PreferencePanes/`

...and then simply delete the file named "*Hosts.prefPane*"

**Comment by specialunderwear** [comment]
Right click the icon in system preference.
Then choose delete.
