### ISSUE TITLE
List Overlaps Headings in Preference Pane

### ISSUE THREAD

**Issue by mikebronner** [specialunderwear/Hosts.prefpane#28]
OS X 10.11.2 (beta) El Capitan

<img width="393" alt="screen shot 2015-11-06 at 09 02 20" src="https://cloud.githubusercontent.com/assets/1791050/11003011/24f26c88-8465-11e5-9a5f-da48829ff13b.png">

**Comment by specialunderwear** [comment]
Something like #23?

Apple solved that, did they break it sfain lol?

**Comment by mikebronner** [comment]
#23 seems completely unrelated? This is a graphical glitch, as shown in the attach image, where the checkboxes and list item text overlap the header row.

**Comment by specialunderwear** [comment]
Haha I meant #25

**Comment by mikebronner** [comment]
Yes, that's it. I'm running on 10.11.2 beta 4, so maybe it will be fixed when they release.
