### ISSUE TITLE
Build Error on OS 10.12.1  XCode 8.2.1 

### ISSUE THREAD

**Issue by JudithOnly** [specialunderwear/Hosts.prefpane#30]
![image](https://cloud.githubusercontent.com/assets/15844852/25688977/366c877e-30b6-11e7-9ed8-1ad7c810ae52.png)

Did anyone have the same problem? I don't know how to use it, I didn't see the edit panel.

**Comment by specialunderwear** [comment]
You need to install bison, with macports or homebrew and you might have to edit the path.
