### ISSUE TITLE
Mojave?

### ISSUE THREAD

**Issue by rctneil** [specialunderwear/Hosts.prefpane#34]
Hey,

Really love this preference pane. Use it all the time. Are you planning on updating it for compatibility with Mojave?  There is a layout issue with the column headers, and dark mode would be cool too! :-)

**Comment by specialunderwear** [comment]
Well seems apple has once again messed up the table rendering, it happened once before and was solved by apple. There is a branch that makes the required transition to arc, but I don't think I'm going to do any crazy new features.

**Comment by rctneil** [comment]
Not even a recompile to support dark mode so it matches the rest of System Preferences? I realise it's not an important feature but would just be a nicety.

**Comment by specialunderwear** [comment]
I don't think xcode will let you recompile a project with garbage collection turned on anymore. However, I'm up for pull requests and  have already prepared a branch with some changes towards ARC!

**Comment by cotfas** [comment]
Any news?

**Comment by specialunderwear** [comment]
No pull requests yet

**Comment by Dirk-** [comment]
@rctneil , @specialunderwear I created a pull request with Dark Mode, ARC and some localizations.

**Comment by specialunderwear** [comment]
So please try the new release, if everything works, thanks @Dirk- https://permanentmarkers.nl/hosts-1.4.1.zip

**Comment by rctneil** [comment]
Works great for me!  Thanks!

**Comment by rctneil** [comment]
Edit: Just tried on Catalina. It fails to open as MacOS says it needs to be updated. Has it been notarized?

**Comment by Dirk-** [comment]
> Edit: Just tried on Catalina. It fails to open as MacOS says it needs to be updated. Has it been notarized? @specialunderwear @Dirk-

No, it hasn't. I'll look into it.

**Comment by Dirk-** [comment]
@rctneil I notarised both the app and the preference pane in my fork of Hosts.prefpane. Please [download](https://github.com/Dirk-/Hosts.prefpane/tree/master/ProductsToInstall) and try them on Catalina. Let me know if it works.

@specialunderwear If it works I'll create a pull request.

**Comment by rctneil** [comment]
Perfect!  Is there a way to download just the preference pane file without the installer?  I like the idea of offering an app version, a preference pane version and an installable preference pane version.

**Comment by Dirk-** [comment]
I can add the built preference pane to the products folder as well, but you cannot notarize a preference pane, you have to distribute it with an installer. So the naked pane will not work with Catalina, I guess.

**Comment by Dirk-** [comment]
Mojave & Catalina compatibility, Dark Mode included in version 1.4.3
