### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by necmettin** [specialunderwear/Hosts.prefpane#36]
When I tried to do a fresh install, macOS warned me that 'Developer ID installer: PermanentMarkers' certificate is expired.

**Comment by specialunderwear** [comment]
Please try the new release: https://permanentmarkers.nl/hosts-1.4.1.zip

**Comment by necmettin** [comment]
Will do, thanks. I assume this fixes the problem. So, closing. Regards.
