### ISSUE TITLE
macOS Catalina issues

### ISSUE THREAD

**Issue by artprojectgroup** [specialunderwear/Hosts.prefpane#38]
After upgrade to Catalina Hosts.prefpane closes and generated this error message:

> Error en las preferencias
> Se ha producido un error en el panel de preferencias Hosts.

Thanks a lot for your great app.

Kind regards.

**Comment by cifrovik** [comment]
That's because it doesn't have disk access. Edit your hosts manually or wait for an update.

**Comment by specialunderwear** [comment]
Please try the update. I tested it on catalina, however I did have the prefPane allready installed, so there could be troubles. https://permanentmarkers.nl/hosts-1.4.1.zip

**Comment by artprojectgroup** [comment]
Updated but can't open it:
No se ha podido cargar el panel de preferencias Hosts.

**Comment by Dirk-** [comment]
@artprojectgroup  I notarised both the app and the preference pane in my fork of Hosts.prefpane. Please [download](https://github.com/Dirk-/Hosts.prefpane/tree/master/ProductsToInstall) and try them on Catalina. Let me know if it works.

**Comment by artprojectgroup** [comment]
Now open but after try to delete anything crash and show this:
Se ha producido un error en el panel de preferencias Hosts.

**Comment by Dirk-** [comment]
What exactly do you mean? I understand it this way:

- The Hosts preferences pane gets installed by the Installer on Catalina.
- You can select it from System Preferences.
- If you try to delete an item of your hosts list, you get the error "An error occurred in the Hosts preference pane."

Is that correct? And is Spanish your system language?

**Comment by nkou123** [comment]
I have the same issue. Initially I get this message twice...
“Hosts.prefPane” can’t be opened because Apple cannot check it for malicious software.

And then I get the message
Could not load Hosts preference pane.

I have tried I think everything.

If you need a log or something I will be happy t sent it to you

**Comment by nkou123** [comment]
I installed with the pkg installer... and not manually and now I am getting another error...

I can see the hosts.... I can deactivate one line... But when I try to activate it back I get 

Preferences Error
There was an error in Hosts preferences.

PS: I am on Catalina also

**Comment by dbedard** [comment]
In trying to install the Hosts PrefPane 1.4.2.pkg
... after autherizing it, I get for following error message:

The operation couldn’t be completed. (com.apple.installer.pagecontroller error -1.)
Couldn’t open “Hosts PrefPane 1.4.2.pkg”.


<img width="424" alt="Screenshot 2020-04-15 at 4 30 44 pm" src="https://user-images.githubusercontent.com/6657567/79385443-969c2b00-7f36-11ea-8967-403dc782f5f6.png">

**Comment by Dirk-** [comment]
@artprojectgroup @nkou123 @dbedard  I think I fixed these Catalina-related issues. The fork is [here](https://github.com/Dirk-/Hosts.prefpane), the pre-built app and pref pane are [here](https://www.dirk-froehling.de/downloads/downloads.html).

**Comment by artprojectgroup** [comment]
Working fine from [here](https://www.dirk-froehling.de/downloads/downloads.html) :-)

Thank you so much.

**Comment by Dirk-** [comment]
This is fixed in version 1.4.3
