### ISSUE TITLE
Could not load Hosts Preferences pane?

### ISSUE THREAD

**Issue by Chunghwa-2018** [specialunderwear/Hosts.prefpane#39]

**Comment by Chunghwa-2018** [comment]
Hosts pref pane refuses to load. I tried removing the pane, removing the installed package.

**Comment by rctneil** [comment]
I too am getting this issue.  @specialunderwear  Is there a solutiion?

**Comment by specialunderwear** [comment]
Try the new release: https://permanentmarkers.nl/hosts-1.4.1.zip

**Comment by kalleboo** [comment]
I have the same issue with 1.4.1.

I also tried "Open Anyway" in the Security & Privacy prefpane with the same result

<img width="780" alt="Screen Shot 2020-02-08 at 17 04 30" src="https://user-images.githubusercontent.com/304806/74082011-d65b1800-4a98-11ea-8140-2ffb1ec18fbf.png">

<img width="660" alt="Screen Shot 2020-02-08 at 17 04 41" src="https://user-images.githubusercontent.com/304806/74082012-d824db80-4a98-11ea-8859-0ffb65041cf7.png">

**Comment by mhulse** [comment]
I had to show the prefpane in my finder, then right click on it and choose open; from there, another dialog will appear and you can click "open". It seems to work from there.

**Comment by Dirk-** [comment]
@kalleboo Please try [my version](https://github.com/Dirk-/Hosts.prefpane/tree/master/ProductsToInstall). It has a notarized installer.

**Comment by Chunghwa-2018** [comment]
@Dirk- 
click the back button
![1583847728423](https://user-images.githubusercontent.com/29922837/76318014-07d53680-6318-11ea-9fd6-f64fb497e38e.jpg)

![1583847352666](https://user-images.githubusercontent.com/29922837/76317412-20911c80-6317-11ea-8a99-0576d016e664.jpg)

**Comment by Chunghwa-2018** [comment]
@Dirk- 
click the  back button.
![1583847728423](https://user-images.githubusercontent.com/29922837/76318368-9053d700-6318-11ea-9c2f-be16a275f570.jpg)
![1583847979431](https://user-images.githubusercontent.com/29922837/76318406-9e095c80-6318-11ea-8291-863496f188be.jpg)

**Comment by Dirk-** [comment]
@Chunghwa-2018 I see this on Catalina, too. Not every time, but sometimes. I will try to track it down.

**Comment by Dirk-** [comment]
@Chunghwa-2018 I fixed that. Please look [here](https://www.dirk-froehling.de/downloads/downloads.html) for the updated prefs pane ("Hosts PrefPane 1.4.3").

**Comment by Dirk-** [comment]
This is fixed in version 1.4.3
