### ISSUE TITLE
Prefpane Icon Size

### ISSUE THREAD

**Issue by joeyhoer** [specialunderwear/Hosts.prefpane#41]
Prefpanes are a bit unusual when it comes to icon sizes. Rather that using the standard 32, 64, 128, 256, 512 icon sizes, Apple uses 80px@2x and 40px@1px icons within the prefpanes, as evidenced by:

```
> identify /System/Library/PreferencePanes/Sidecar.prefPane/Contents/Resources/SidecarPrefPane.tiff 
/System/Library/PreferencePanes/Sidecar.prefPane/Contents/Resources/SidecarPrefPane.tiff[0] TIFF 80x80 80x80+0+0 8-bit sRGB 11824B 0.010u 0:00.002
/System/Library/PreferencePanes/Sidecar.prefPane/Contents/Resources/SidecarPrefPane.tiff[1] TIFF 40x40 40x40+0+0 8-bit sRGB 0.010u 0:00.001
````

It might be worthwhile updating the icon size to give it a crisp appearance.

**Comment by specialunderwear** [comment]
What makes you think that hosts does not use 40px icon? Note that the project also contains a regular app, which I tried to release in the app store but apple #@&!!

**Comment by Dirk-** [comment]
Icon now is "crisp" in version 1.4.3
