### ISSUE TITLE
Hosting releases on GitHub

### ISSUE THREAD

**Issue by strauhmanis** [specialunderwear/Hosts.prefpane#42]
Hi!

permanentmarkers.nl is unreachable.

Please host the latest release here on GitHub.

Thanks!

**Comment by noahmaranesi** [comment]
Yep, very frustrating. Please @specialunderwear.

**Comment by Dirk-** [comment]
@noahmaranesi @strauhmanis I forked the project and made a Catalina-compatible version. The fork is [here](https://github.com/Dirk-/Hosts.prefpane), the pre-built app and pref pane are [here](https://www.dirk-froehling.de/downloads/downloads.html).

**Comment by strauhmanis** [comment]
@Dirk- 
Thank you, Dirk!
