### ISSUE TITLE
After Upgrade to Big Sur

### ISSUE THREAD

**Issue by VSHoward** [specialunderwear/Hosts.prefpane#46]
Unable to access Hosts module after upgrading to Big Sur. Receiving message "Preferences Error There was an error in Hosts Preferences". I tried re-installing, but that did not clear the issue. 
![2020-11-23_12-45-55](https://user-images.githubusercontent.com/3145309/99996561-ea52da80-2d89-11eb-8b9f-a797dc515524.png)

**Comment by Dirk-** [comment]
So this is on an Intel Mac, right? I will look into it as soon as I can update one of my Macs to Big Sur.

**Comment by VSHoward** [comment]
Correct. 2.9 GHz 6-Core **Intel Core i9** with 32 GB 2400 MHz DDR4. Thank you!

**Comment by Maxusz666** [comment]
Ok

**Comment by dformdotdk** [comment]
Can confirm the issue... also on Intel Mac

**Comment by Dirk-** [comment]
@VSHoward , @denovoit  Which version are you using? Is it v1.4.5? This version works for me on a virtual machine with macOS 11.0.1. Please look at `/Library/PreferencePanes` for `Hosts.prefPane`.

If not, please try to reinstall from https://github.com/Dirk-/Hosts.prefpane/releases/tag/v1.4.5

Also, is the app working?

**Comment by VSHoward** [comment]
@Dirk- Looks like I was running an old version. I installed the package from your link above and it works fine now. Thanks.

**Comment by Dirk-** [comment]
v1.4.5 works on Big Sur
